import type { Metadata } from "next";
import { Clicker_Script, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const ClickerScript = Clicker_Script({ subsets: ["latin"], variable: "--font-clicker-script", weight: ["400"] })
const PlayFairDisplay = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair-display", weight: ["400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ClickerScript.variable} ${PlayFairDisplay.variable}`}>{children}</body>
    </html>
  );
}
